export const LOGIN_TYPE_PARAM = {
  MOBILE_VCODE: 'MOBILE_VCODE',
  EMAIL_PASSWORD: 'EMAIL_PASSWORD',
  MOBILE_PASSWORD: 'MOBILE_PASSWORD',
  EMAIL_VCODE: 'EMAIL_VCODE'
}

export const LOGIN_TYPE = {
  SMS: 'SMS',
  ACCOUNT: 'ACCOUNT'
}
export const REGISTER_TYPE = {
  SMS: 'SMS',
  EMAIL: 'EMAIL'
}
