// ** I18n Imports
import { useTranslation } from 'react-i18next'

// ** MUI Imports
import Grid from '@mui/material/Grid'
import Box from '@mui/material/Box'
import Hidden from '@mui/material/Hidden'

// ** Page Components Imports
import Section from '../../components/Section'
import HRPlan from '../../HRPlan'
import Button from '@mui/material/Button'
import Typography from '@mui/material/Typography'

import { Icon } from '@iconify/react'
import JoinUsWrap from '../../JoinUsWrap'
import AutoTitle from '../../../components/auto-title'
import Link from 'next/link'
import {beforeWrite} from "@popperjs/core";

export interface CasePreviewProps {
  onRequestDemo: (value: boolean) => void
}

const infoCard2Data: {url: string,title: string, desc: string}[] = [
  {
    url: '/images/home/platform/virtual-currency/Frame 2.png',
    title: 'Higher efficiency',
    desc: 'By using USDC USDT payments, companies no longer need to convert their funds into fiat currency to operate global payroll. This is an end-to-end encrypted cryptocurrency payment experience with near-instant settlement.'
  },
  {
    url: '/images/home/platform/virtual-currency/Frame-1.png',
    title: 'Lower costs',
    desc: 'There is no need to pay the fees associated with SWIFT generated by bank transfers, nor does it increase payroll costs due to exchange rate fluctuations. On the employee side, it effectively prevents losses caused by inflation of local currencies.'
  },
  {
    url: '/images/home/platform/virtual-currency/Frame.png',
    title: 'No intermediaries',
    desc: 'Companies holding USDC can pay TeleHire directly through their Coinbase account to pay for the salaries and payments of their global team.'
  },
]

const rightDataList: {title: string, desc: string}[] = [
  {
    title: 'Set up encrypted payroll account',
    desc: 'Setting up encrypted payroll on Coinbase and selecting direct deposit from the setup menu. Follow the instructions to generate a unique encrypted payroll account number and routing number.'
  },
  {
    title: 'Fill in the payment method.',
    desc: 'Add the encrypted payroll account number and routing number generated in the first step to the way you receive your salary on Telehire.'
  },
  {
    title: 'Continued payroll receipt.',
    desc: 'On the monthly payment date, TeleHire will transfer the employee\'s salary to their designated Coinbase account.'
  },
  {
    title: 'Easily convert to local fiat currency.',
    desc: 'After receiving the encrypted payroll, employees/contractors can choose to hold the encrypted currency for savings or easily convert it to local fiat currency for spending.'
  },
]

const infoCard1Data: {url: string,title: string, desc: string}[] = [
  {
    url: '/images/home/platform/virtual-currency/Frame 3.png',
    title: 'Flexible Control Over Token Ownership and Vesting',
    desc: 'TeleHire solves challenges throughout the entire token grant lifecycle from design and structure to managing ownership, vesting, payroll integration, and withholding tax.'
  },
  {
    url: '/images/home/platform/virtual-currency/Frame-4.png',
    title: 'Global-Compliant Token Grant Management',
    desc: 'Help your employees fully utilize their token incentive rewards without worrying about local tax compliance, no matter where they are located.'
  },
  {
    url: '/images/home/platform/virtual-currency/Frame-3.png',
    title: 'Tax Savings, Anywhere in the World',
    desc: 'We are committed to establishing and processing compliant and tax-saving treatment for your organization\'s and your employees\' grant structures.'
  },
  {
    url: '/images/home/platform/virtual-currency/Frame-2.png',
    title: 'Token Grant Design',
    desc: 'Setting up and managing your token grant structure throughout its lifecycle is key to ensuring compliance for your organization and employees in relevant jurisdictions.'
  },
]

const PartTime = (casePreviewProps: CasePreviewProps) => {
  const { onRequestDemo } = casePreviewProps
  const { t, i18n } = useTranslation()

  const infoCard1 = (url: string, title: string, desc:string) => {
    return (
      <Grid item xs={12} sm={2.8} sx={{display: 'flex',alignItems: 'center', flexDirection: 'column', borderRadius: 3,border: '1px solid #3A35411F', pt: 20, mx: 'auto', mb: 3, px: 9, backgroundColor: '#F9FAFC'}}>
        <Box component="img" src={url} width={112} sx={{mb: 14}}  />
        <Grid item sx={{width: '100%', textAlign: 'center',}}>
          <Typography sx={{fontSize: 20, fontWeight: 600, color :'#564A96', mb: 5,}}>{t(title)}</Typography>
          <Typography sx={{fontSize: 14, fontWeight: 400, color :'#3A3541DE', mb: 20, }}>{t(desc)}</Typography>
        </Grid>
      </Grid>
    )
  }

  const infoCard2 = (url: string, title: string, desc:string) => {
    return (
      <Grid item xs={12} sm={3.8} sx={{display: 'flex',alignItems: 'center', flexDirection: 'column', borderRadius: 3,border: '1px solid #3A35411F', pt: 15, mx: 'auto', mb: 3, px: 9, backgroundColor: '#F9FAFC'}}>
        <Box component="img" src={url} width={112} sx={{mb: 14}}  />
        <Grid item sx={{width: '100%', textAlign: 'center',}}>
          <Typography sx={{fontSize: 24, fontWeight: 600, color :'#564A96', mb: 5,}}>{t(title)}</Typography>
          <Typography sx={{fontSize: 14, fontWeight: 400, color :'#3A3541DE', mb: 20, }}>{t(desc)}</Typography>
        </Grid>
      </Grid>
    )
  }

  return (
    <>
      <Grid item xs={12} sm={12}>
        <Grid
          container
          justifyContent='center'
          alignItems='center'
          sx={{
            backgroundColor: '#7C4DFF',
            height: 560,
            mb: 27.5
          }}
        >
          <Hidden smDown>
            <Grid item sm={1.5} />
          </Hidden>
          <Grid item sm={3.5} xs={12} sx={{px: 2}}>
            <Typography sx={{fontSize: 42, fontWeight: 600, color :'#fff', mb: 4.5}}>{t('Paying Global Teams with Cryptocurrency')}</Typography>
            <Typography sx={{fontSize: 14, fontWeight: 400, color :'#fff'}}>
              {t('The demand for cryptocurrency wages among global remote workers is skyrocketing, coming from both companies looking to pay their teams with cryptocurrency balances and team members seeking to earn income in digital currencies. In Latin America, most remote workers prefer to receive their wages in cryptocurrency due to various reasons, including the instability of the local legal tender\'s exchange rate and the impact of high local inflation.')}
            </Typography>
          </Grid>
          <Hidden smDown>
            <Grid item sm={1} />
          </Hidden>
          <Grid item sm={3} xs={12}>
            <Box
              component='img'
              src={`/images/home/platform/virtual-currency/virtual-currency-back.png`}
              sx={theme => ({
                [theme.breakpoints.up('sm')]: { maxWidth: 750 },
              })}
            />
          </Grid>
          <Hidden smDown>
            <Grid item sm={2} />
          </Hidden>
        </Grid>
      </Grid>
      <Section sx={{ background: '#fff' }}>
        <AutoTitle title={t('One-click payment of global team salary bills')} />
        <Grid container md={12} sm={12} sx={{display: 'flex', alignItems: 'center', mb: 35}}>
          <Grid item xs={12} sm={6.5} sx={{mb: 4}}>
            <Box
              component='img'
              src={`/images/home/platform/virtual-currency/first-left.png`}
              sx={theme => ({
                [theme.breakpoints.up('sm')]: { maxWidth: 750 },
              })}
            />
          </Grid>
          <Hidden smDown>
            <Grid sm={0.5}></Grid>
          </Hidden>
          <Grid item xs={12} sm={4}>
            <Typography sx={{fontSize: 24, fontWeight: 700, color :'#3A3541DE', mb: 1,textAlign: 'left'}}>
              01/
            </Typography>
            <Grid sx={{textAlign: 'center', display: 'flex'}}>
              <Typography sx={{backgroundColor: '#3A3541', width: 6, height: 6,borderRadius: 3, mt: 2, mr: 2}} />
              <Typography sx={{fontSize: 15, fontWeight: 400, color :'#3A3541', mb: 9, flex: 1, textAlign: 'left', lineHeight: '180%'}}>
                {t('So far, the demand for cryptocurrency wages is on the rise, coming from both companies looking to pay their teams with company cryptocurrency balances and team members seeking to earn income in digital currencies. We see a 10% increase in demand for cryptocurrency wage payments every month.')}
              </Typography>
            </Grid>
            <Typography sx={{fontSize: 24, fontWeight: 700, color :'#3A3541DE', mb: 1,textAlign: 'left'}}>
              02/
            </Typography>
            <Grid sx={{textAlign: 'center', display: 'flex'}}>
              <Typography sx={{backgroundColor: '#3A3541', width: 6, height: 6,borderRadius: 3, mt: 2, mr: 2}} />
              <Typography sx={{fontSize: 16, fontWeight: 400, color :'#3A3541', mb: 16, flex: 1, textAlign: 'left', lineHeight: '180%'}}>
                {t('TeleHire has enabled the use of cryptocurrency withdrawals for global employees, allowing anyone paid through TeleHire to directly withdraw their income in the form of Bitcoin, Ethereum, USDC, Solana, and Dash to their Coinbase account, with almost instant withdrawals.')}
              </Typography>
            </Grid>
          </Grid>
          <Hidden smDown>
            <Grid sm={1}></Grid>
          </Hidden>
        </Grid>
      </Section>
      <Section sx={{ background: '#fff' }}>
        <AutoTitle title={t('Why Choose Cryptocurrency to Pay Wages?')} />
        <Grid container md={12} sx={{mb: 37}}>
          {
            infoCard2Data.map(v => {
              return infoCard2(v.url, v.title, v.desc)
            })
          }
        </Grid>
      </Section>
      <Section sx={{ background: '#fff' }}>
        <Grid container sx={{display: 'flex', alignItems: 'center' ,justifyContent:'center', mb: 20}}>
          <AutoTitle title="coinbase" />
          <Typography sx={{backgroundColor: '#564A96', width: 8, height: 8,borderRadius: 3, mx: 5, mb: 15}} />
          <AutoTitle title={t('Cryptocurrency payroll for employees')} />
        </Grid>
        <Grid container md={12}>
          <Grid xs={12} sm={3.7}>
            <Box component="img" src="/images/home/platform/virtual-currency/Left.png" />
          </Grid>
          <Hidden smDown>
            <Grid sm={1} />
          </Hidden>
          <Grid xs={12} sm={7} sx={{mb: 40}}>
            {
              rightDataList.map((v: {title: string, desc: string}, index: number) => (
                <Grid item xs={12} sm={12} sx={{display: 'flex', height: 166, border: '1px solid #3A35411F', borderRadius: 3, pt: 9, px: 11, mb: 10}}>
                  <Grid item sx={{color: '#fff', backgroundColor: '#7C4DFF', minWidth: 35, height: 35, borderRadius: 4.5, fontSize: 21, fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', mr: 6.5, mt: 1}}>
                    {index + 1}
                  </Grid>
                  <Grid>
                    <Typography sx={{fontSize: 24, fontWeight: 600, color :'#564A96', mb: 5,textAlign: 'left'}}>
                      {t(v.title)}
                    </Typography>
                    <Typography sx={{fontSize: 14, fontWeight: 400, color :'#3A3541DE',textAlign: 'left', lineHeight: '160%'}}>
                      {t(v.desc)}
                    </Typography>
                  </Grid>
                </Grid>
              ))
            }

          </Grid>
        </Grid>
      </Section>
      <Section sx={{ background: '#fff' }}>
        <AutoTitle title={t('Ensuring global compliance with cryptocurrency payroll and tax regulations for your peace of mind.')} />
        <Grid container md={12} sx={{mb: 37}}>
          <Grid item xs={12} sm={5.5} sx={{borderRadius: 3, overflow: 'hidden'}}>
            <Grid container md={12} sm={5.8}>
              <Hidden smDown>
                <Grid item xs={12} sm={6.5} sx={{px: 10, pt: 19 ,backgroundColor: '#F9FAFC'}}>
                  <Typography sx={{fontSize: 28, fontWeight: 600, color :'##2E2E2E', mb: 5}}>{t('For Enterprises')}</Typography>
                  <Typography sx={{fontSize: 18, fontWeight: 400, color :'#3A3541DE'}}>{t('Attract, retain, and manage your global workforce through our compliant employment and symbolic compensation solutions.')}</Typography>
                </Grid>
                <Grid item xs={12} sm={5.5}>
                  <Box component="img" src='/images/home/platform/virtual-currency/group-left.png'  />
                </Grid>
              </Hidden>
              <Hidden smUp>
                <Grid item xs={7} sm={6.5} sx={{px: 5, pt: 6 ,backgroundColor: '#F9FAFC'}}>
                  <Typography sx={{fontSize: 18, fontWeight: 600, color :'##2E2E2E', mb: 5}}>{t('For Enterprises')}</Typography>
                  <Typography sx={{fontSize: 14, fontWeight: 400, color :'#3A3541DE'}}>{t('Attract, retain, and manage your global workforce through our compliant employment and symbolic compensation solutions.')}</Typography>
                </Grid>
                <Grid item xs={5} sm={5.5}>
                  <Box component="img" src='/images/home/platform/virtual-currency/group-left.png'  />
                </Grid>
              </Hidden>
            </Grid>
          </Grid>
          <Hidden smDown>
            <Grid sm={0.4} />
          </Hidden>
          <Grid item xs={12} sm={5.8} sx={{borderRadius: 3, overflow: 'hidden'}}>
            <Hidden smDown>
              <Grid container md={12} sm={5.5}>
                <Grid item xs={12} sm={6.5} sx={{px: 10, pt: 19, backgroundColor: '#F9FAFC'}}>
                  <Typography sx={{fontSize: 28, fontWeight: 600, color :'##2E2E2E', mb: 5}}>{t('For Startups')}</Typography>
                  <Typography sx={{fontSize: 18, fontWeight: 400, color :'#3A3541DE'}}>{t('Reduce operational expenses and scale effectively through our cryptocurrency payroll and tax compliance solutions.')}</Typography>
                </Grid>
                <Grid item xs={12} sm={5.5}>
                  <Box component="img" src='/images/home/platform/virtual-currency/group-right.png'  />
                </Grid>
              </Grid>
            </Hidden>
            <Hidden smUp>
              <Grid container md={12} sm={5.5}>
                <Grid item xs={7} sm={6.5} sx={{px: 5, pt: 6, backgroundColor: '#F9FAFC'}}>
                  <Typography sx={{fontSize: 18, fontWeight: 600, color :'##2E2E2E', mb: 5}}>{t('For Startups')}</Typography>
                  <Typography sx={{fontSize: 14, fontWeight: 400, color :'#3A3541DE'}}>{t('Reduce operational expenses and scale effectively through our cryptocurrency payroll and tax compliance solutions.')}</Typography>
                </Grid>
                <Grid item xs={5} sm={5.5}>
                  <Box component="img" src='/images/home/platform/virtual-currency/group-right.png'  />
                </Grid>
              </Grid>
            </Hidden>
          </Grid>
        </Grid>
      </Section>
      <Section sx={{ background: '#fff' }}>
        <AutoTitle title={t('Grant Long-Term Token Incentives for Your Team')} />
        <Typography sx={{fontSize: 32, fontWeight: 600, color :'#564A96', mb: 6,textAlign: 'center'}}></Typography>
        <Typography sx={{fontSize: 18, fontWeight: 400, color :'#3A3541DE', mb: 12,textAlign: 'center'}}>{t('TeleHire offers token grant management solutions that include global-compliant legal templates, payroll integration including withholding, tax, and reporting, as well as real-time helpdesk support for grantees.')}</Typography>
        <Grid container md={12} sx={{mb: 37}}>
          {
            infoCard1Data.map(v => {
              return infoCard1(v.url, v.title, v.desc)
            })
          }
        </Grid>
      </Section>
      <JoinUsWrap onRequestDemo={onRequestDemo} />
    </>
  )
}

export default PartTime
